var cartas = document.getElementById("cards");
var ocultarMain = document.getElementById("main");
var medisCompras = document.getElementById("mediCompras");
var pacienCompras = document.getElementById("pacienCompras");
var medisVentas = document.getElementById("mediVentas");
var empleeVentas = document.getElementById("empleeVentas");
var proveeVentas = document.getElementById("proveeVentas");
var proveeListar = document.getElementById("proveeListar");
var pacienteListar = document.getElementById("pacienteListar");
var recetaListar = document.getElementById("recetaListar");
var agregaMedi = document.getElementById("agregaMedi");
var agregaProvee = document.getElementById("agregaProvee");
var agregaPaciente = document.getElementById("agregaPaciente");


var medis = document.getElementById("listarMedis");
medis.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    proveeListar.style.display = "none";
    proveeVentas.style.display = "none";
    empleeVentas.style.display = "none";
    medisVentas.style.display = "none"
    pacienCompras.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "flex";
    cartas.style.alignItems = "center";
    cartas.style.justifyContent = "center";
    cartas.style.flexWrap = "wrap";
    cartas.style.gap = "5%";
    cartas.style.marginTop = "6%";
});

var medicamentoComprado = document.getElementById("litMedisCompras");
medicamentoComprado.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    proveeListar.style.display = "none";
    proveeVentas.style.display = "none";
    empleeVentas.style.display = "none";
    medisVentas.style.display = "none"
    pacienCompras.style.display = "none";
    cartas.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "flex";
    medisCompras.style.alignItems = "center";
    medisCompras.style.justifyContent = "center";
    medisCompras.style.flexWrap = "wrap";
    medisCompras.style.gap = "5%";
    medisCompras.style.marginTop = "6%";
    medisCompras.style.height = "100vh";
});

var pacienteCompra = document.getElementById("listPacienCompras");
pacienteCompra.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    proveeListar.style.display = "none";
    proveeVentas.style.display = "none";
    empleeVentas.style.display = "none";
    medisVentas.style.display = "none"
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "flex";
    pacienCompras.style.alignItems = "center";
    pacienCompras.style.justifyContent = "center";
    pacienCompras.style.flexWrap = "wrap";
    pacienCompras.style.gap = "5%";
    pacienCompras.style.marginTop = "6%";
});

var medisVenta = document.getElementById("listMedisVentas");
medisVenta.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    proveeListar.style.display = "none";
    proveeVentas.style.display = "none";
    empleeVentas.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "flex";
    medisVentas.style.alignItems = "center";
    medisVentas.style.justifyContent = "center";
    medisVentas.style.flexWrap = "wrap";
    medisVentas.style.gap = "5%";
    medisVentas.style.marginTop = "6%";
});

var empleVentas = document.getElementById("listEmpleVentas");
empleVentas.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    proveeListar.style.display = "none";
    proveeVentas.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "flex";
    empleeVentas.style.alignItems = "center";
    empleeVentas.style.justifyContent = "center";
    empleeVentas.style.flexWrap = "wrap";
    empleeVentas.style.gap = "5%";
    empleeVentas.style.marginTop = "6%";
});

var listProvedoVenta = document.getElementById("listProveeVentas");
listProvedoVenta.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    proveeListar.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "flex";
    proveeVentas.style.alignItems = "center";
    proveeVentas.style.justifyContent = "center";
    proveeVentas.style.flexWrap = "wrap";
    proveeVentas.style.gap = "5%";
    proveeVentas.style.marginTop = "6%";
});

var proveeList = document.getElementById("listarProvee");
proveeList.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    pacienteListar.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "none";
    proveeListar.style.display = "flex";
    proveeListar.style.alignItems = "center";
    proveeListar.style.justifyContent = "center";
    proveeListar.style.flexWrap = "wrap";
    proveeListar.style.gap = "5%";
    proveeListar.style.marginTop = "6%";
});

var pacientList = document.getElementById("listarPaciente");
pacientList.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    recetaListar.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "none";
    proveeListar.style.display = "none";
    pacienteListar.style.display = "flex";
    pacienteListar.style.alignItems = "center";
    pacienteListar.style.justifyContent = "center";
    pacienteListar.style.flexWrap = "wrap";
    pacienteListar.style.gap = "5%";
    pacienteListar.style.marginTop = "6%";
});

var recetaList = document.getElementById("listarReceta");
recetaList.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "none";
    proveeListar.style.display = "none";
    pacienteListar.style.display = "none";
    recetaListar.style.display = "flex";
    recetaListar.style.alignItems = "center";
    recetaListar.style.justifyContent = "center";
    recetaListar.style.flexWrap = "wrap";
    recetaListar.style.gap = "5%";
    recetaListar.style.marginTop = "6%";
});

var aggMedica = document.getElementById("aggMedica");
aggMedica.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "none";
    proveeListar.style.display = "none";
    pacienteListar.style.display = "none";
    recetaListar.style.display = "none";
    agregaMedi.style.display = "flex";
    agregaMedi.style.alignItems = "center";
    agregaMedi.style.justifyContent = "center";
    agregaMedi.style.flexWrap = "wrap";
    agregaMedi.style.gap = "5%";
    agregaMedi.style.marginTop = "6%";
});

var aggProvee = document.getElementById("aggProvee");
aggProvee.addEventListener("click", function(){
    comProveA.style.display = "none";
    agregaPaciente.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "none";
    proveeListar.style.display = "none";
    pacienteListar.style.display = "none";
    recetaListar.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "flex";
    agregaProvee.style.alignItems = "center";
    agregaProvee.style.justifyContent = "center";
    agregaProvee.style.flexWrap = "wrap";
    agregaProvee.style.gap = "5%";
    agregaProvee.style.marginTop = "6%";
});

var aggPacient = document.getElementById("aggPacient");
aggPacient.addEventListener("click", function(){
    pacienCompraPara = "none";
    pacienCompraPara2023 = "none";
    pacienNoCompra2023 = "none";
    medicamentosTotaParace = "none";
    medicamentosVenMazo2023 = "none";
    medicamentosMenosVen2023 = "none";
    medicamentosPromeXVen = "none";
    medicamentosNoVendidos = "none";
    medicamentosVenXMes2023 = "none";
    medicamentosVenPorMes2023 = "none";
    medicamentosNoVendidos2023 = "none";
    medicamentosTotalTrimes2023 = "none";
    ventaXEmpleado = "none";
    empleadoMas5Ventas = "none";
    empleadoSinVentas2023 = "none";
    empleadoMenos5Ventas = "none";
    empleVenMedicDistinto2023 = "none";
    empleadoSinVentasAbril2023 = "none";
    totalMedisVenXProveedor = "none";
    proveeNoVenMedicUltiAño = "none";
    proveedorSumiMasMedic2023 = "none";
    proveedoresSumiMedic2023 = "none";
    proveeSumiMas5MedicDife2023 = "none";
    medicamentosMenos50Stock = "none";
    medicamentosVencenAntes2024 = "none";
    totalRecaudadoXVenMedic = "none";
    medicamentoMasCaro = "none";
    medicamentosPre50Stock100 = "none";
    proveeInfoContacto = "none";
    cantMedicXProvee = "none";
    ganaciaXProvee2023 = "none";
    proveeMenos50Medic = "none";
    pacienteMasDinero2023 = "none";
    totalGastXPacientrecetasDespues2023 = "none";


    comProveA.style.display = "none";
    ocultarMain.style.display = "none";
    medisCompras.style.display = "none";
    cartas.style.display = "none";
    pacienCompras.style.display = "none";
    medisVentas.style.display = "none";
    empleeVentas.style.display = "none";
    proveeVentas.style.display = "none";
    proveeListar.style.display = "none";
    pacienteListar.style.display = "none";
    recetaListar.style.display = "none";
    agregaMedi.style.display = "none";
    agregaProvee.style.display = "none";
    agregaPaciente.style.display = "flex";
    agregaPaciente.style.alignItems = "center";
    agregaPaciente.style.justifyContent = "center";
    agregaPaciente.style.flexWrap = "wrap";
    agregaPaciente.style.gap = "5%";
    agregaPaciente.style.marginTop = "6%";
});

var comProveA = document.getElementById("medicamentosProveeA");
var pacienCompraPara = document.getElementById("pacienCompraPara");
var pacienCompraPara2023 = document.getElementById("pacienCompraPara2023");
var pacienNoCompra2023 = document.getElementById("pacienNoCompra2023");
var medicamentosTotaParace = document.getElementById("medicamentosTotaParace");
var medicamentosVenMazo2023 = document.getElementById("medicamentosVenMazo2023");
var medicamentosMenosVen2023 = document.getElementById("medicamentosMenosVen2023");
var medicamentosPromeXVen = document.getElementById("medicamentosPromeXVen");
var medicamentosNoVendidos = document.getElementById("medicamentosNoVendidos");
var medicamentosVenXMes2023 = document.getElementById("medicamentosVenXMes2023");
var medicamentosVenPorMes2023 = document.getElementById("medicamentosVenPorMes2023");
var medicamentosNoVendidos2023 = document.getElementById("medicamentosNoVendidos2023");
var medicamentosTotalTrimes2023 = document.getElementById("medicamentosTotalTrimes2023");
var ventaXEmpleado = document.getElementById("ventaXEmpleado");
var empleadoMas5Ventas = document.getElementById("empleadoMas5Ventas");
var empleadoSinVentas2023 = document.getElementById("empleadoSinVentas2023");
var empleadoMenos5Ventas = document.getElementById("empleadoMenos5Ventas");
var empleVenMedicDistinto2023 = document.getElementById("empleVenMedicDistinto2023");
var empleadoSinVentasAbril2023 = document.getElementById("empleadoSinVentasAbril2023");
var totalMedisVenXProveedor = document.getElementById("totalMedisVenXProveedor");
var proveeNoVenMedicUltiAño = document.getElementById("proveeNoVenMedicUltiAño");
var proveedorSumiMasMedic2023 = document.getElementById("proveedorSumiMasMedic2023");
var proveedoresSumiMedic2023 = document.getElementById("proveedoresSumiMedic2023");
var proveeSumiMas5MedicDife2023 = document.getElementById("proveeSumiMas5MedicDife2023");
var medicamentosMenos50Stock = document.getElementById("medicamentosMenos50Stock");
var medicamentosVencenAntes2024 = document.getElementById("medicamentosVencenAntes2024");
var totalRecaudadoXVenMedic = document.getElementById("totalRecaudadoXVenMedic");
var medicamentoMasCaro = document.getElementById("medicamentoMasCaro");
var medicamentosPre50Stock100 = document.getElementById("medicamentosPre50Stock100");
var proveeInfoContacto = document.getElementById("proveeInfoContacto");
var cantMedicXProvee = document.getElementById("cantMedicXProvee");
var ganaciaXProvee2023 = document.getElementById("ganaciaXProvee2023");
var proveeMenos50Medic = document.getElementById("proveeMenos50Medic");
var pacienteMasDinero2023 = document.getElementById("pacienteMasDinero2023");
var totalGastXPacient = document.getElementById("totalGastXPacient");
var recetasDespues2023 = document.getElementById("recetasDespues2023");


var medicComProveeA = document.getElementById("comProveA");
medicComProveeA.addEventListener("click", function(){
    medisCompras.style.display = "none";
    comProveA.style.display = "flex";
});